### ISSUE TITLE
Docstrings for manifold projection

### ISSUE THREAD

**Issue by quantumjot** [quantumjot/cellx#13]
The docstrings for the manifold projection functions need improving: https://github.com/quantumjot/cellx/blob/3bc751bc020b5f9d6ddd85f487f9240583cc9201/cellx/tools/projection.py#L27-L31

**Comment by quantumjot** [comment]
@laureho - do you want to take a look at improving this?

**Comment by laureho** [comment]
yup, I'm on it!
