### ISSUE TITLE
Define `self._image_files` to store image filenames

### ISSUE THREAD

**Issue by laureho** [quantumjot/cellx#21]
Currently, the list of image filenames is not stored anywhere if `preload_images = False`. Need to add an `else` condition that defines `self._image_files` (used in line 113) to account for that.
https://github.com/quantumjot/cellx/blob/425d1e6bb21e9243f8cd5be46a9235d23f3df2fc/cellx/tools/projection.py#L53-L55
https://github.com/quantumjot/cellx/blob/bf43be1720b9445ffbdd855dd60bec2d936d5405/cellx/tools/projection.py#L113

**Comment by quantumjot** [comment]
Closed with #34
