### ISSUE TITLE
Add heatmap to tools/projection.py

### ISSUE THREAD

**Issue by laureho** [quantumjot/cellx#25]
It would be helpful to add a heatmap plot to the projection to visualize how many example image patches are grouped in each block of the grid. This would help understand the distribution of the image data in different areas of the grid, since the projection only shows one image per grid block.

https://github.com/quantumjot/cellx/blob/4cad596ccfaef08f37e1a3210fa28cfda180734c/cellx/tools/projection.py#L128-L145

**Comment by quantumjot** [comment]
Great idea! Perhaps you could use the bin statistics to do this. There are counts associated with each bin in the projection:

https://github.com/quantumjot/cellx/blob/c1d0048d1efcbaf27e468b363a3003ae40d61090/cellx/tools/projection.py#L92-L99

The returned variable `s` is the binned statistic, in this case `"count"` and should be an array of dimensions (bins, bins).

**Comment by quantumjot** [comment]
This is done now:
https://github.com/quantumjot/cellx/commit/87cd7a12adc7cbafe9d14aadbec23c87e04bc60a
