### ISSUE TITLE
Function read_annotations to read only a specified zipfile

### ISSUE THREAD

**Issue by KristinaUlicna** [quantumjot/cellx#29]
In the `read_annotations` function: https://github.com/quantumjot/cellx/blob/0d0455324ec9d42010b75f59311a1f24dcc826b2/cellx/tools/io.py#L184 
perhaps it would be cool to include an optional argument `annotation_file` to allow importing only data from single specific zip file. 

*Default:* `annotation_file=None` will extract the image patches from all the zipfiles in the root path, otherwise `None` could be replaced by `str` such as `annotation_03-08-2021--13-39-57.zip` and only the contents of this zip file would be exported.

**Utility:** excluding the patches which were mistakenly labelled after visualising them in https://github.com/lowe-lab-ucl/cnn-annotator/blob/907e517997910709f7d36b7d86a493205688d43b/notebooks/B_CNN_Data_Preview_Images.ipynb

**Comment by quantumjot** [comment]
How about a compromise:
```python
def read_annotations(path: Union[str, list], use_flagged: bool = False):
```
so that if `path` is a list, it uses it as a list of files to read, and if it's a string, interpret it either as a single file, or (if a path) load all of the zip files in that directory?

**Comment by quantumjot** [comment]
Do you want to give it a go and open a PR?
